platform :ios, '13.0'

target 'P&G_Code_Challenge' do
  use_frameworks!

  # Pods for P&G_Code_Challenge
  pod "SwiftUIRefresh"

  target 'P&G_Code_ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'P&G_Code_ChallengeUITests' do
    # Pods for testing
  end

end
